### ISSUE TITLE
Creating check boxes in iform

### ISSUE THREAD

**Issue by msd135** [Indicia-Team/Indicia-support#1]
Hi,

I have created a new project at http://thesolitarybeeproject.org and in several of the tabs would like to include check boxes so for example, the number of bees sited 1-10 10-15 20-3 50+

Any ideas how this can be accomplished?

Thanks

Mark

**Comment by msd135** [comment]
Just as a suplement, the look that I am attemptiong to create for the form is as described below:

Submit Sighting:

·         The wizard should consist of two tabs:   What did you see? And Where did you see it?

·         The what did you see tab should include everything except for location information.

·         All of the questions should be multiple choice with dropdown lists.

·

**Comment by JimBacon** [comment]
This sounds like a question for the Indicia forum, http://forums.nbn.org.uk/viewforum.php?id=25

**Comment by BirenRathod** [comment]
Thanks Jim, I know, I will ask Mark to put question on Indicia Forum.
